name: Handle xyz123 Branch Merges

on:
  pull_request:
    types:
      - closed

jobs:
  say-hello-on-xyz123-merge:
    if: github.event.pull_request.merged == true &&
        github.event.pull_request.base.ref == 'main' &&
        contains(github.event.pull_request.head.ref, 'xyz123')
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "hello world"
