name: Release Trigger

on:
  release:
    types: [published, created, edited]  # 'created' for draft, 'published' for final release

jobs:
  on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print release info
        run: |
          echo "Release name: ${{ github.event.release.name }}"
          echo "Tag: ${{ github.event.release.tag_name }}"
          echo "Is draft? ${{ github.event.release.draft }}"
          echo "Is prerelease? ${{ github.event.release.prerelease }}"
